print("Name: Arjit Kumar Singh \nRoll: 071 \nBranch: BCA 'B' 2nd Year")
print("\n")

print("                  *                                    ")
print("                 * *                             *    ")
print("                *  *   * * * * * * * * * * * * * * * * * ")
print("               *   *                       *     * ")
print("              *    *                             *  ")
print("             * * * *  *  ***    *****      *     * ")
print("  * * *     *      *   *    *        *     *     *  ")
print(" *         *       *   *             *     *     * ")
print("*         *        *   *             *     *     *   ")
print(" *       *         *   *             *     *     * ")
print("  *     *          *   *             *     *     *  ")
print("   *  *                          *   *                ")
print("                                  * *                 ")
print("                                                       ")